name 'mojolingo-openshift'
version '0.1.0'
source 'git://github.com/mojolingo/puppet-openshift.git'
author 'Ben Klang'
license 'MIT'
summary 'Module for installing Asterisk'
description 'Configures a node to participate in an OpenShift cluster'
project_page 'https://github.com/mojolingo/puppet-openshift'
dependency 'puppetlabs/apt', '>= 0.0.4'
dependency 'puppetlabs/ntp', '>= 0.1.0'
